version: "3"
services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://postgres:password@db/backpack_dev

  db:
    image: postgres
    environment:
      POSTGRES_DB: backpack_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
